<a href="https://colab.research.google.com/github/RheedWhan/AltSchool_DataScience_2023/blob/main/09_Introduction_to_Numpy_and_Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy and Pandas

## Learning Objectives
By the end of this lesson, you should be able to:
* Perform basic operations in Numpy;
* Perform basic operations in Pandas; and
* Analyse data using Numpy and Pandas.

## Outline
* Introduce the Numpy Python library and some of its functionality;
* Introduce the Pandas Python and some of its functionality; and
* Load, manipulate, and analyse data using Numpy and Pandas.

## Introduction

Python has many packages for working with data and performing operations like the loading, analysing and storing of data. Numpy and Pandas are two commonly used and useful ones. In this train, you will learn some of the basic operations in Numpy and Pandas.

# Numpy
Numpy is a Python package which provides high-performance, multidimensional array objects, numerical computing tools, and is fundamental in scientific computing. It is the core library for scientific computing in Python ([see the full documentation](https://numpy.org/)). We will start by defining what an array is, how to create an array, how to access and modify an array, and look at useful functions on arrays. Finally, we will identify when an array should be the chosen data structure when performing data analysis or manipulation.

### What is an Array?
Similar to that of a Python list, a numpy array is a data structure which stores multiple values. The main difference between the two is that lists can contain heterogeneous data types (combinations of `str`, `int`, even `list`), whilst numpy arrays can only store values of the same data type. Numpy arrays can be thought of as a grid of values and can be multi-dimensional.

Numpy arrays are stored more efficiently than Python lists and allow mathematical operations to be vectorized, which results in significantly higher performance than with looping constructs in Python.

### Creating a Numpy Array
If we want to work with any numpy objects or functions we first need to import the Numpy library.


In [ ]:
import numpy as np

To make a numpy array, you use the `np.array()` function. All you need to do is pass a list to it and optionally, you can specify the data type of the data. Let's look at an example:

In [ ]:
# Create an array by passing in a list of lists.
ratings = np.array([[94,89,63], [93,92,48], [92,94,56]])

ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

You can see that there are 3 rows and columns in this array. We can inspect the shape of the array by using its `shape` attribute. This will return a tuple of integers giving the size of the array along each dimension.

In [ ]:
ratings.shape

(3, 3)

We can also create arrays using the following functions:

* `np.ones()` - array of ones
* `np.zeros()` - array of zeros
* `np.random.random()` - array with random values

Let's look at some examples:

In [ ]:
# Create an array of ones - pass in shape as a tuple.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Create an array of zeros - pass in shape as a tuple.
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Create an array of random values - pass in shape as a tuple.
np.random.random((3,3))

array([[0.55032346, 0.98985146, 0.76593356],
       [0.74523266, 0.15435135, 0.09976193],
       [0.1017914 , 0.26573559, 0.51662041]])

### Accessing Numpy Arrays
Numpy offers several ways to index into arrays. Here, we'll work through slicing, and Boolean array indexing.

#### Slicing
Similar to Python lists, Numpy arrays can be sliced. Since arrays may be multi-dimensional, you must specify a slice for each dimension of the array, where the slices per dimension is split by a comma. For a 2-D array, the first dimension is the vertical axis while the second dimension is the horizontal axis. For a 2-D array:

* `np.array[vertical index , horizontal index]` - for one element
* `np.array[vertical start:vertical end , horizontal start:horizontal end]` - for more than one element

Let's look at a few examples:

In [ ]:
# Whole array.
ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [ ]:
# Select top left element.
ratings[0,0]

94

In [ ]:
# Select first row.
ratings[0,:]

array([94, 89, 63])

In [ ]:
# Select first column.
ratings[:,0]

array([94, 93, 92])

In [ ]:
# Select first two rows and first two columns.
ratings[0:2,0:2]

array([[94, 89],
       [93, 92]])

#### Boolean Array Indexing
Boolean array indexing let's you pick out a selection of elements from an array. This type of indexing is often used to select the elements of an array which satisfy a specific condition. The syntax is as follows:

* `np.array[condition]`

Let's look at an example:

In [ ]:
# Select all values greater than 90.
ratings[ratings > 90]

array([94, 93, 92, 92, 94])

### Modifying Numpy Arrays
We will now look at how to add elements to an array, followed by how to remove elements from an array.

#### Adding Elements
Adding elements can be done by using the `np.append()` function. This will add elements to the end of an array. Let's look at an example:

In [ ]:
# Append an extra row - note that axis=0.
ratings_extra_row = np.append(ratings, [[92, 88, 78]], axis=0)

ratings_extra_row

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56],
       [92, 88, 78]])

#### Removing Elements
Deleting elements can be done by using the `np.delete()` function. This will delete elements at the specified indices. Let's look at an example:

In [ ]:
# Delete the 3rd row - note that axis=0.
ratings_del_row = np.delete(ratings, [2], axis=0)

ratings_del_row

array([[94, 89, 63],
       [93, 92, 48]])

### Functions on Numpy Arrays
There are various functions we can perform on numpy arrays. We will look at a few of them, namely:

* `np.array.sum()`
* `np.array.min()`
* `np.array.max()`

In all these functions we can pass an axis argument. This will allow us to sum the columns and rows separately. Let's look at examples:

In [ ]:
# Sum of all elements in array.
ratings.sum()

721

In [ ]:
# Sum of each row.
ratings.sum(axis=1)

array([246, 233, 242])

In [ ]:
# Min of each row.
ratings.min(axis=1)

array([63, 48, 56])

In [ ]:
# Max of each column.
ratings.max(axis=0)

array([94, 94, 63])

### When to use Numpy Arrays

A Numpy array is a data structure which stores multiple values, all of the same data type, and can be multi-dimensional. We should use a Numpy array if all of the following statements hold:

* We have multi-dimensional data
* All entries are of the same data type

Numpy arrays are also preferred over list of lists due to efficiency and functionality.

## Pandas

In this section we will look at Pandas dataframes, which is most commonly used for any Python data analysis. We will define what a Pandas dataframe is, show how to create dataframes and how to access them.

### What is a Pandas Dataframe?
Pandas is a data manipulation tool which is built on the Numpy package. Pandas' key data structure is the `dataframe`. A dataframe allows for the storage and manipulation of tabular data. It is a two-dimensional labelled data structure.


Basically, you could say that the Pandas dataframe consists of three main components: the data, index, and columns. Let's walk through some examples to gain an understanding of these components.

#### Creating a Dataframe
We can create a dataframe by calling the `DataFrame()` constructor. The main arguments in the constructor are the data, index and columns. The data that is passed in can be in the form of other data structures (lists, dictionaries or numpy arrays) or by loading in a file.

Let's start our examples by first importing the Pandas library:

In [ ]:
import pandas as pd

#### Dataframes from other Data Structures

We now look at some examples on how to create a dataframe from various data structures in Python.

Using **lists**, we need to create a list of lists (nested list) with the relevant data. We then also need to pass an index (player names in this example) and column names.

In [ ]:
# Create list of lists containing data.
list_df = [[32, 'Portugal', 94], [30, 'Argentina', 93], [25 , 'Brazil', 92]]

# Create index - names of players.
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create column names.
columns = ['Age', 'Nationality', 'Overall']

# Create dataframe by passing in data, index and columns.
pd.DataFrame(data=list_df, index=index, columns=columns)

Age Nationality  Overall
Christiano Ronaldo   32    Portugal       94
Lionel Messi         30   Argentina       93
Neymar               25      Brazil       92

Using **dictionaries**, we need to create a dictionary with the relevant data.

The keys should be the column names, while the values should be the data entries for that column. We then also need to pass an index. Note that because the keys account for the column names, we don't have to pass in an argument for columns.

In [ ]:
# Create dictionary containing data.
dict_df = {'Age':[32, 30, 25], 'Nationality':['Portugal', 'Argentina', 'Brazil'], 'Overall':[94, 93, 92]}

# Create index - names of players.
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create dataframe by passing in data, index and columns.
pd.DataFrame(data=dict_df, index=index)

Age Nationality  Overall
Christiano Ronaldo   32    Portugal       94
Lionel Messi         30   Argentina       93
Neymar               25      Brazil       92

Using **numpy arrays**, we need to create a numpy array with the relevant data. We then also need to pass an index (player names) and column names.

In [ ]:
# Create numpy array containing data.
array_df = np.array([[32, 'Portugal', 94], [30, 'Argentina', 93], [25 , 'Brazil', 92]])

# Create index - names of players.
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create column names.
columns = ['Age', 'Nationality', 'Overall']

# Create dataframe by passing in data, index and columns.
pd.DataFrame(data=array_df, index=index, columns=columns)

Age Nationality Overall
Christiano Ronaldo  32    Portugal      94
Lionel Messi        30   Argentina      93
Neymar              25      Brazil      92

#### Dataframes from other files
The data argument can also be a loaded file. We will load the full csv file. Pandas make it very easy to do this; you simply load the data using the `read_csv()` function and pass in the full path of the file as a string.

Pandas will use the first row as columns so we don't need to pass column names. We can also specify the index when we load the data by passing our index column as a string under the index_col argument.

In [ ]:
# Load data - pass 'Name' as our index column.
# For this exercise, we'll use football player data to evaluate our dataframe.


# Create dataframe called df.
df = pd.read_csv(r"C:\Users\Ojo Ridwan\Desktop\Notebooks\fifa.csv") # load the data here.

# Use the head() function to look at the first 5 rows.
df.head()

C:\Users\Ojo Ridwan\AppData\Local\Temp\ipykernel_25976\2178283603.py:6: DtypeWarning: Columns (14,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Ojo Ridwan\Desktop\Notebooks\fifa.csv") # load the data here.


Name  Age Nationality  Overall Acceleration Aggression  \
0  Cristiano Ronaldo   32    Portugal       94       89         63       
1           L. Messi   30   Argentina       93       92         48       
2             Neymar   25      Brazil       92       94         56       
3          L. Suárez   30     Uruguay       92       88         78       
4           M. Neuer   31     Germany       92       58         29       

  Agility Balance Ball control Composure  ... Short passing Shot power  \
0  89      63           93        95      ...        83         94       
1  90      95           95        96      ...        88         85       
2  96      82           95        92      ...        81         80       
3  86      60           91        83      ...        83         87       
4  52      35           48        70      ...        55         25       

  Sliding tackle Sprint speed Stamina Standing tackle Strength  Vision  \
0         23           91      92              31       80      85       
1         26           87      73              28       59      90       
2         33           90      78              24       53      80       
3         38           77      89              45       80      84       
4         11           61      44              10       83      70       

  Volleys Preferred Positions  
0  88                  ST LW   
1  85                     RW   
2  83                     LW   
3  88                     ST   
4  11                     GK   

[5 rows x 39 columns]

We use the `head()` function to only look at the first 5 records of our data. This is helpful if the dataframe has many rows and loading it will take lots of time.

### Accessing Dataframes

Accessing data within dataframes is not as straightforward as with the previous data structures. This can be done by index, by column, or by both. Let's work through these methods.

#### By Index
To access by index only in a dataframe we can use the `iloc` or `loc` functions with the indices in square brackets. The `iloc` function refers to the index location, so we pass in the number of the index, while the `loc` function refers to the name of the index, so we pass in the index name. Use slicing if you want more than one index. Eg:

* `dataframe.iloc[index i]` - returns series at index i
* `dataframe.iloc[index start: index end]` - returns dataframe from start to end (end not included)
* `dataframe.loc['index name']` - returns series of given index name

Let's look at a few examples:

In [ ]:
# Select the 5th row using iloc[].
df.iloc[4]

Name                   M. Neuer
Age                          31
Nationality             Germany
Overall                      92
Acceleration             58    
Aggression               29    
Agility                  52    
Balance                  35    
Ball control             48    
Composure                70    
Crossing                 15    
Curve                    14    
Dribbling                30    
Finishing                13    
Free kick accuracy       11    
GK diving                91    
GK handling              90    
GK kicking               95    
GK positioning           91    
GK reflexes              89    
Heading accuracy         25    
Interceptions            30    
Jumping                  78    
Long passing             59    
Long shots               16    
Marking                  10    
Penalties                47    
Positioning              12    
Reactions                85    
Short passing            55    
Shot power               25    
Sliding 

In [ ]:
# Select rows 5 to 10.
df.iloc[4:10]

Name  Age Nationality  Overall Acceleration Aggression Agility  \
4        M. Neuer   31     Germany       92       58         29      52       
5  R. Lewandowski   28      Poland       91       79         80      78       
6          De Gea   26       Spain       90       57         38      60       
7       E. Hazard   26     Belgium       90       93         54      93       
8        T. Kroos   27     Germany       90       60         60      71       
9      G. Higuaín   29   Argentina       90       78         50      75       

  Balance Ball control Composure  ... Short passing Shot power Sliding tackle  \
4  35           48        70      ...        55         25             11       
5  80           89        87      ...        83         88             19       
6  43           42        64      ...        50         31             13       
7  91           92        87      ...        86         79             22       
8  69           89        85      ...        90         87             69       
9  69           85        86      ...        75         88             18       

  Sprint speed Stamina Standing tackle Strength  Vision Volleys  \
4       61      44              10       83      70      11       
5       83      79              42       84      78      87       
6       58      40              21       64      68      13       
7       87      79              27       65      86      79       
8       52      77              82       74      88      82       
9       80      72              22       85      70      88       

  Preferred Positions  
4                 GK   
5                 ST   
6                 GK   
7                 LW   
8             CDM CM   
9                 ST   

[6 rows x 39 columns]

In [ ]:
# Select the M. Neuer index using loc[].
df.loc[df['Name'] == 'M. Neuer']

Name  Age Nationality  Overall Acceleration Aggression Agility Balance  \
4  M. Neuer   31     Germany       92       58         29      52      35       

  Ball control Composure  ... Short passing Shot power Sliding tackle  \
4       48        70      ...        55         25             11       

  Sprint speed Stamina Standing tackle Strength  Vision Volleys  \
4       61      44              10       83      70      11       

  Preferred Positions  
4                 GK   

[1 rows x 39 columns]

#### By Column
To access by column only we can simply call `dataframe['Column Name']`. If we want more than one column we input a list of column names inside the square brackets:

* `dataframe['Column Name']` - returns series of given column
* `dataframe[['Column 1', 'Column 2']]` - returns dataframe with the given columns

Let's look at examples.

In [ ]:
# Select the column 'Age'.
df['Age']

0        32
1        30
2        25
3        30
4        31
         ..
17976    17
17977    47
17978    17
17979    18
17980    18
Name: Age, Length: 17981, dtype: int64

In [ ]:
# Select the columns 'Age' and 'Nationality'.
df[['Age', 'Nationality']]

Age Nationality
0       32    Portugal
1       30   Argentina
2       25      Brazil
3       30     Uruguay
4       31     Germany
...    ...         ...
17976   17     England
17977   47     England
17978   17    Scotland
17979   18     England
17980   18       Ghana

[17981 rows x 2 columns]

#### By index and column
We can also select a subset of the dataframe using indices and columns in combination. Let's look at a few examples:

In [ ]:
# Select the first 5 rows and first 2 columns - Rows first.
df.iloc[0:5][['Age', 'Nationality']]

Age Nationality
0   32    Portugal
1   30   Argentina
2   25      Brazil
3   30     Uruguay
4   31     Germany

In [ ]:
# Select the first 5 rows and first 2 columns - Columns first.
df[['Age', 'Nationality']].iloc[0:5]

Age Nationality
0   32    Portugal
1   30   Argentina
2   25      Brazil
3   30     Uruguay
4   31     Germany

Transforming some values in the Name Column, to find occurrences of 'L. Suárez' and replace them with 'L. Suarez. replacing the 'á' will make it easier to index the player with your keyboard.

In [ ]:
df['Name'] = df['Name'].str.replace('L. Suárez', 'L. Suarez')

C:\Users\Ojo Ridwan\AppData\Local\Temp\ipykernel_25976\178125146.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace('L. Suárez', 'L. Suarez')


In [ ]:
df['Name']

0        Cristiano Ronaldo
1                 L. Messi
2                   Neymar
3                L. Suarez
4                 M. Neuer
               ...        
17976            A. Kelsey
17977        B. Richardson
17978             J. Young
17979         J. Lundstram
17980            L. Sackey
Name: Name, Length: 17981, dtype: object

### When to use Dataframes
Unlike the Numpy array which is suited for storing and performing computations on homogeneous data (data of the same type), Pandas dataframes can accommodate heterogeneous data. This makes them the choice data structure for manipulating often messy data (e.g tabular data from spreadsheets, or SQL tables).

We should use a Pandas dataframe if all of the following statements hold:

* We have 2-dimensional data (rows and columns)
* The data type is the same within a column
* We are interested in the index (rows) and column names

## Exercises

Here are some exercises for you to try out. The solutions can be found at the end of this train.

#### Exercise 1:
Select rows 9-14 of the football player dataframe we've just been using.

In [ ]:
df.iloc[9:15]

Name  Age Nationality  Overall Acceleration Aggression Agility  \
9     G. Higuaín   29   Argentina       90       78         50      75       
10  Sergio Ramos   31       Spain       90       75         84      79       
11  K. De Bruyne   26     Belgium       89       76         68      80       
12   T. Courtois   25     Belgium       89       46         23      61       
13    A. Sánchez   28       Chile       89       88         80      90       
14     L. Modrić   31     Croatia       89       75         62      93       

   Balance Ball control Composure  ... Short passing Shot power  \
9   69           85        86      ...        75         88       
10  60           84        80      ...        78         79       
11  75           87        84      ...        90         85       
12  45           23        52      ...        32         36       
13  87           87        86      ...        81         84       
14  94           92        84      ...        92         73       

   Sliding tackle Sprint speed Stamina Standing tackle Strength  Vision  \
9          18           80      72              22       85      70       
10         91           77      84              89       81      63       
11         40           75      87              51       73      90       
12         16           52      38              18       70      44       
13         35           84      85              39       72      83       
14         73           71      82              80       58      90       

   Volleys Preferred Positions  
9   88                     ST   
10  66                     CB   
11  82              RM CM CAM   
12  12                     GK   
13  83            RM LW ST LM   
14  74                 CDM CM   

[6 rows x 39 columns]

#### Exercise 2:
Select, in order, only the "Preferred Positions", "Overall" and "Age" columns for the football player Neymar.

In [ ]:
df.loc[df['Name'] == 'Neymar'][["Preferred Positions","Overall","Age"]]

Preferred Positions  Overall  Age
2                 LW        92   25

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Name                 17981 non-null  object
 1   Age                  17981 non-null  int64 
 2   Nationality          17981 non-null  object
 3   Overall              17981 non-null  int64 
 4   Acceleration         17981 non-null  object
 5   Aggression           17981 non-null  object
 6   Agility              17981 non-null  object
 7   Balance              17981 non-null  object
 8   Ball control         17981 non-null  object
 9   Composure            17981 non-null  object
 10  Crossing             17981 non-null  object
 11  Curve                17981 non-null  object
 12  Dribbling            17981 non-null  object
 13  Finishing            17981 non-null  object
 14  Free kick accuracy   17981 non-null  object
 15  GK diving            17981 non-null  object
 16  GK h

#### Exercise 3:
Select, in order, only the "Overall", "Age" and "Nationality" columns for all players with ages of 35 years or older

In [ ]:
df[df['Age'] >= 35][["Overall", "Age",  "Nationality"]]

Overall  Age     Nationality
18          89   39           Italy
31          88   35          Sweden
68          86   35  Czech Republic
91          85   36           Italy
126         84   36           Spain
...        ...  ...             ...
17577       52   38           Japan
17586       52   36           Japan
17605       52   39    Saudi Arabia
17617       52   37         England
17977       46   47         England

[468 rows x 3 columns]

## Conclusion
In this train, you learned to perform basic operations using more Numpy and Pandas, you also learnt how to load, manipulate and analyse data using these packages. The reader is expected to complete the exercises before moving forward to ensure familiarity with these packages.

## Appendix
- [Basic Numpy Functionality](https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array)

- [Numpy package home page](https://numpy.org)

- [Pandas package home page](https://pandas.pydata.org/)